name: Deploy Plugin to Live Site

on:
  push:
    branches:
      - main # or "master" if that's your default

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: sftp
          port: 3453
          local-dir: ./product-search.php # your local plugin folder
          server-dir: /site/public_html/wp-content/plugins/product-search/
          exclude: |
            **/.git*
            **/.github*
            **/node_modules/**
            **/vendor/**
            **/*.md
            **/*.yml
            **/*.yaml
            **/*.json
            **/*.DS_Store
