name: Deploy Plugin via SFTP

on:
  push:
    branches:
      - main # change if your repo uses 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload plugin via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          server: ${{ secrets.FTP_SERVER }}
          port: 3452
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_path: "./product-search.php"
          remote_path: "/site/public_html/wp-content/plugins/product-search/"
          args: >-
            -avzr --delete --progress
            --exclude=".git*"
            --exclude=".github*"
            --exclude="node_modules/"
            --exclude="vendor/"
            --exclude="*.md"
            --exclude="*.yml"
            --exclude="*.yaml"
            --exclude="*.json"
            --exclude="*.DS_Store"
